db-uri = "postgres://postgres@127.0.0.1:5432/tugpt_test"
db-schema = "public"
db-anon-role = "anon"
server-host = "127.0.0.1"
server-port = 3000
jwt-secret = "test-jwt-secret-for-phase3b-transport-tests-only"
