-- Invitations: close the direct-write hole, and give the flow a real lifecycle.
--
-- ============================================================================
-- WHY THIS IS A MIGRATION AND NOT WIRING
-- ============================================================================
--
-- The roadmap has this item at 2 engineer-days, described as "wiring, not
-- building", because the table, the RPC, the RLS policies and ten pgTAP
-- assertions already exist and nothing calls them. That estimate was made
-- before anyone looked at what the existing policies actually permit.
--
-- `20260716000001` grants `authenticated` INSERT and UPDATE directly on
-- `organization_invitations` (line 660), and the INSERT policy (line 600)
-- checks only that the caller is an owner or admin of the org and that
-- `invited_by = auth.uid()`. Every other column is the caller's to choose.
-- So an ADMIN can, with one PostgREST insert and no RPC involved:
--
--   1. Set `role = 'owner'` and invite someone — or themselves at a second
--      identity — into a role above their own. Privilege escalation by proxy.
--   2. Choose `token_hash` themselves. The column is named for a hash, but
--      nothing computes one: whatever value the client sends IS the bearer
--      credential. An admin can therefore mint an invitation whose token they
--      know without it ever being mailed to the invitee.
--   3. Set `expires_at` to any date. The 7-day default is a default, not a
--      bound.
--
-- and with UPDATE, mutate a pending invitation's `role` after it was created
-- and reviewed.
--
-- None of that is reachable through a UI, because there is no UI. It is
-- reachable today by anyone holding an admin session and an HTTP client, which
-- is the threat model that matters for a multi-tenant product.
--
-- ============================================================================
-- WHAT CHANGES
-- ============================================================================
--
-- Writes move behind SECURITY DEFINER RPCs and the direct grants go away.
-- SELECT stays, because an admin listing pending invitations is a legitimate
-- read and RLS already scopes it to their org.
--
--   private.create_invitation   owner/admin only, cannot exceed own role,
--                               server-generated token, one pending per email
--   private.revoke_invitation   owner/admin only, pending only
--   private.accept_invitation   rewritten (see below)
--
-- ============================================================================
-- THE TOKEN MODEL, WHICH WAS THE ACTUAL DEFECT
-- ============================================================================
--
-- `accept_invitation(p_token_hash, p_user_id)` took the *hash* as its
-- argument. A hash you can present is not a hash — it is the password. The
-- column stored the same value the caller sends, so `token_hash` provided
-- exactly no protection: anyone with read access to the table held every live
-- invitation credential in usable form.
--
-- Now the RPC takes the *plaintext* token and hashes it internally. The
-- plaintext is generated by `create_invitation` (§5 explains why from
-- `gen_random_uuid` rather than `gen_random_bytes`), returned to the caller
-- exactly once, and never stored. A database read yields only SHA-256
-- digests, which are not presentable.
--
-- `p_user_id` is also gone. It was checked against `auth.uid()` and could
-- therefore only ever be one value; taking it as a parameter meant every
-- caller had to be trusted to pass the right one, and the check had to be
-- correct. Deriving it is one fewer thing to get wrong.
--
-- ============================================================================
-- ACCEPTING AN INVITATION NEVER CHANGES AN EXISTING ROLE
-- ============================================================================
--
-- The old body ended with:
--
--     ON CONFLICT (organization_id, user_id) DO UPDATE SET role = EXCLUDED.role
--
-- so accepting a stale invitation rewrote the accepter's current role. Both
-- directions are wrong. Upward it is escalation: an invitation issued months
-- ago at `admin`, never revoked, promotes a user who has since been moved to
-- `viewer`. Downward it is a denial-of-service on the org's own owner, who
-- accepts an old `agent` invitation and loses control of the organization.
--
-- Role changes are a separate operation with separate authorization. An
-- invitation now creates a membership or it does nothing to one; the RPC
-- reports which happened, and marks the invitation accepted either way so it
-- cannot be replayed.
--
-- ============================================================================
-- TYPED ERRORS
-- ============================================================================
--
-- Every failure was `RAISE EXCEPTION` with no ERRCODE, which PostgreSQL
-- reports as P0001 and the API error mapper turns into HTTP 500. "Your
-- invitation expired" is not a server error, and a 500 tells the invitee to
-- try again — which cannot work. These map to real status codes:
--
--   P3D01  404  not found / not a member / bad token  (one answer, on purpose)
--   P3D02  403  caller's role may not do this
--   P3D03  409  a pending invitation already exists for this address
--   P3D04  409  invitation is not pending
--   P3D05  410  invitation expired
--   P3D06  403  this invitation was issued to a different address
--   P3D07  409  already a member of this organization
--   P3D08  403  cannot invite above your own role
--   P3D09  422  malformed email
--
-- P3D01 covers "no such invitation", "you are not in that organization" and
-- "that token does not match", deliberately: an attacker walking token or id
-- space must not be able to tell a wrong guess from a revoked one, or discover
-- which organization ids exist by watching the error change.

-- ---------------------------------------------------------------------------
-- 1. Status vocabulary
-- ---------------------------------------------------------------------------

-- `declined` already exists and means the invitee said no. Revocation by an
-- admin is a different event with a different actor, and collapsing them would
-- make the audit trail lie about who ended the invitation.
ALTER TYPE public.invitation_status ADD VALUE IF NOT EXISTS 'revoked';

-- ---------------------------------------------------------------------------
-- 2. One live invitation per address per organization
-- ---------------------------------------------------------------------------

-- Without this, "invite" is an unbounded append: the same person can hold
-- fifty pending invitations at five different roles, and which one they
-- happen to click decides their permissions. Partial, so the history of
-- accepted and revoked invitations is preserved.
--
-- Lowercased because email is case-insensitive in every way that matters here,
-- and `accept_invitation` already compared with LOWER().
CREATE UNIQUE INDEX IF NOT EXISTS idx_org_invitations_one_pending_per_email
  ON public.organization_invitations (organization_id, LOWER(email))
  WHERE status = 'pending';

-- Listing pending invitations for an org is the admin screen's main query.
CREATE INDEX IF NOT EXISTS idx_org_invitations_org_status
  ON public.organization_invitations (organization_id, status, created_at DESC);

-- ---------------------------------------------------------------------------
-- 3. Bound the expiry window at the table
-- ---------------------------------------------------------------------------

-- The RPC sets this and the RPC is now the only writer, so this is a backstop
-- rather than the enforcement. It exists because the cost of a wrong value is
-- an invitation that is valid forever, and a CHECK is cheaper than trusting
-- every future edit of the function body.
ALTER TABLE public.organization_invitations
  DROP CONSTRAINT IF EXISTS organization_invitations_expiry_bounded;

ALTER TABLE public.organization_invitations
  ADD CONSTRAINT organization_invitations_expiry_bounded
  CHECK (expires_at > created_at AND expires_at <= created_at + INTERVAL '30 days');

-- ---------------------------------------------------------------------------
-- 4. Role ordering, so "cannot invite above yourself" is expressible
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION private.role_rank(p_role public.organization_role)
RETURNS INTEGER
LANGUAGE sql
IMMUTABLE
SET search_path = pg_catalog, public
AS $$
  SELECT CASE p_role
    WHEN 'owner'   THEN 50
    WHEN 'admin'   THEN 40
    WHEN 'manager' THEN 30
    WHEN 'agent'   THEN 20
    WHEN 'viewer'  THEN 10
  END;
$$;

COMMENT ON FUNCTION private.role_rank(public.organization_role) IS
  'Total order over organization_role. Gaps of ten so a role can be inserted '
  'between two existing ones without renumbering. NULL for an unknown role, '
  'which makes any comparison against it false — the safe direction.';

-- ---------------------------------------------------------------------------
-- 5. Token generation and hashing
-- ---------------------------------------------------------------------------

-- Two v4 UUIDs, hyphens stripped: 64 hex characters carrying 244 bits of
-- entropy. `gen_random_bytes` would be the obvious choice and is not used
-- because it lives in pgcrypto, whose schema differs between this database and
-- a local harness; `gen_random_uuid` and `sha256` are both in pg_catalog, so
-- this function has no extension dependency and cannot break on a search_path
-- difference between environments.
CREATE OR REPLACE FUNCTION private.new_invitation_token()
RETURNS TEXT
LANGUAGE sql
VOLATILE
SET search_path = pg_catalog
AS $$
  SELECT replace(gen_random_uuid()::text, '-', '') ||
         replace(gen_random_uuid()::text, '-', '');
$$;

CREATE OR REPLACE FUNCTION private.hash_invitation_token(p_token TEXT)
RETURNS TEXT
LANGUAGE sql
IMMUTABLE
SET search_path = pg_catalog
AS $$
  SELECT encode(sha256(convert_to(p_token, 'UTF8')), 'hex');
$$;

COMMENT ON FUNCTION private.hash_invitation_token(TEXT) IS
  'The only way a token becomes a token_hash. Deliberately not exposed through '
  'a public wrapper: a caller who can hash on demand can verify guesses '
  'offline against a stolen table, which is most of what storing a hash was '
  'meant to prevent.';

-- ---------------------------------------------------------------------------
-- 6. create_invitation
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION private.create_invitation(
  p_organization_id UUID,
  p_email TEXT,
  p_role public.organization_role
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, private, pg_temp
AS $$
DECLARE
  v_actor UUID := auth.uid();
  v_actor_role public.organization_role;
  v_email TEXT := lower(btrim(p_email));
  v_token TEXT;
  v_id UUID;
  v_expires TIMESTAMPTZ;
BEGIN
  IF v_actor IS NULL THEN
    RAISE EXCEPTION 'Authentication required' USING ERRCODE = 'P3D01';
  END IF;

  -- Membership and role in one read. A non-member gets P3D01, the same answer
  -- as a nonexistent organization: an authenticated stranger must not be able
  -- to discover which organization ids exist by watching the error change.
  SELECT role INTO v_actor_role
  FROM public.organization_members
  WHERE organization_id = p_organization_id AND user_id = v_actor;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Organization not found' USING ERRCODE = 'P3D01';
  END IF;

  IF v_actor_role NOT IN ('owner', 'admin') THEN
    RAISE EXCEPTION 'Role may not invite' USING ERRCODE = 'P3D02';
  END IF;

  -- The escalation ceiling. Without it an admin can mint an owner, which is
  -- the same as making themselves one via a second address they control.
  IF private.role_rank(p_role) > private.role_rank(v_actor_role) THEN
    RAISE EXCEPTION 'Cannot invite above your own role' USING ERRCODE = 'P3D08';
  END IF;

  IF v_email IS NULL OR v_email = '' OR position('@' IN v_email) < 2 THEN
    RAISE EXCEPTION 'Invalid email' USING ERRCODE = 'P3D09';
  END IF;

  -- Inviting an existing member produces a token that can never do anything.
  -- Refusing here is the difference between a clear message now and a
  -- confused person clicking a dead link tomorrow.
  IF EXISTS (
    SELECT 1
    FROM public.organization_members m
    JOIN public.profiles pr ON pr.id = m.user_id
    WHERE m.organization_id = p_organization_id AND lower(pr.email) = v_email
  ) THEN
    RAISE EXCEPTION 'Already a member' USING ERRCODE = 'P3D07';
  END IF;

  -- Sweep first. `status` does not become 'expired' on its own — nothing runs
  -- on a timer, and `accept_invitation` cannot mark it (see the comment there).
  -- So a pending-but-expired row would sit under the partial unique index
  -- forever and make the address permanently un-invitable: the person's
  -- invitation lapses, and re-inviting them fails with "already pending" about
  -- an invitation that can no longer be accepted. Found by the existing pgTAP
  -- suite the first time this index existed.
  UPDATE public.organization_invitations
  SET status = 'expired', updated_at = now()
  WHERE organization_id = p_organization_id
    AND lower(email) = v_email
    AND status = 'pending'
    AND expires_at < now();

  v_token := private.new_invitation_token();
  v_expires := now() + INTERVAL '7 days';

  BEGIN
    INSERT INTO public.organization_invitations
      (organization_id, email, role, token_hash, invited_by, expires_at)
    VALUES
      (p_organization_id, v_email, p_role,
       private.hash_invitation_token(v_token), v_actor, v_expires)
    RETURNING id INTO v_id;
  EXCEPTION WHEN unique_violation THEN
    -- The partial unique index. Revoke the live one first, deliberately,
    -- rather than quietly replacing it and leaving two valid tokens.
    RAISE EXCEPTION 'A pending invitation already exists for this address'
      USING ERRCODE = 'P3D03';
  END;

  INSERT INTO public.audit_logs (organization_id, user_id, action, resource, details)
  VALUES (p_organization_id, v_actor, 'invitation.create', 'invitation',
          jsonb_build_object('invitation_id', v_id, 'role', p_role));

  -- The token is returned exactly once and is not stored. If the caller loses
  -- it, the invitation is revoked and reissued; there is no recovery path, and
  -- there should not be one.
  RETURN jsonb_build_object(
    'invitation_id', v_id,
    'token', v_token,
    'email', v_email,
    'role', p_role,
    'expires_at', v_expires
  );
END;
$$;

-- ---------------------------------------------------------------------------
-- 7. revoke_invitation
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION private.revoke_invitation(p_invitation_id UUID)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, private, pg_temp
AS $$
DECLARE
  v_actor UUID := auth.uid();
  v_actor_role public.organization_role;
  v_inv RECORD;
BEGIN
  IF v_actor IS NULL THEN
    RAISE EXCEPTION 'Authentication required' USING ERRCODE = 'P3D01';
  END IF;

  SELECT * INTO v_inv
  FROM public.organization_invitations
  WHERE id = p_invitation_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Invitation not found' USING ERRCODE = 'P3D01';
  END IF;

  SELECT role INTO v_actor_role
  FROM public.organization_members
  WHERE organization_id = v_inv.organization_id AND user_id = v_actor;

  -- Not-a-member and not-found are the same answer, for the same reason as
  -- create_invitation: invitation ids must not be probeable across tenants.
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Invitation not found' USING ERRCODE = 'P3D01';
  END IF;

  IF v_actor_role NOT IN ('owner', 'admin') THEN
    RAISE EXCEPTION 'Role may not revoke' USING ERRCODE = 'P3D02';
  END IF;

  IF v_inv.status <> 'pending' THEN
    RAISE EXCEPTION 'Invitation is not pending' USING ERRCODE = 'P3D04';
  END IF;

  UPDATE public.organization_invitations
  SET status = 'revoked', updated_at = now()
  WHERE id = p_invitation_id;

  INSERT INTO public.audit_logs (organization_id, user_id, action, resource, details)
  VALUES (v_inv.organization_id, v_actor, 'invitation.revoke', 'invitation',
          jsonb_build_object('invitation_id', p_invitation_id));

  RETURN jsonb_build_object('invitation_id', p_invitation_id, 'status', 'revoked');
END;
$$;

-- ---------------------------------------------------------------------------
-- 8. accept_invitation, rewritten
-- ---------------------------------------------------------------------------

-- The old two-argument form is dropped rather than kept alongside. It has zero
-- callers (verified by grep across apps/ and packages/ before this migration),
-- and leaving a function that accepts a presentable hash would leave the hole
-- open next to its own fix.
DROP FUNCTION IF EXISTS private.accept_invitation(TEXT, UUID);
DROP FUNCTION IF EXISTS public.accept_invitation(TEXT, UUID);

CREATE OR REPLACE FUNCTION private.accept_invitation(p_token TEXT)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, private, pg_temp
AS $$
DECLARE
  v_user UUID := auth.uid();
  v_email TEXT;
  v_inv RECORD;
  v_existing public.organization_role;
  v_created BOOLEAN := false;
BEGIN
  IF v_user IS NULL THEN
    RAISE EXCEPTION 'Authentication required' USING ERRCODE = 'P3D01';
  END IF;

  SELECT lower(email) INTO v_email FROM public.profiles WHERE id = v_user;
  IF v_email IS NULL THEN
    RAISE EXCEPTION 'Profile not found' USING ERRCODE = 'P3D01';
  END IF;

  SELECT * INTO v_inv
  FROM public.organization_invitations
  WHERE token_hash = private.hash_invitation_token(p_token)
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Invalid invitation' USING ERRCODE = 'P3D01';
  END IF;

  -- Identity is checked before status, so that someone holding a token issued
  -- to another address learns nothing about whether it is still live.
  IF lower(v_inv.email) <> v_email THEN
    RAISE EXCEPTION 'Invitation was issued to a different address'
      USING ERRCODE = 'P3D06';
  END IF;

  IF v_inv.status <> 'pending' THEN
    RAISE EXCEPTION 'Invitation is no longer pending' USING ERRCODE = 'P3D04';
  END IF;

  IF v_inv.expires_at < now() THEN
    -- The original wrote `status = 'expired'` here and then raised. The raise
    -- aborts the function, which rolls back its own UPDATE, so the row was
    -- never actually marked — the statement looked like bookkeeping and did
    -- nothing. plpgsql has no autonomous transaction to fix that with, so the
    -- sweep lives in `create_invitation` instead, where it runs on a path that
    -- commits.
    RAISE EXCEPTION 'Invitation has expired' USING ERRCODE = 'P3D05';
  END IF;

  SELECT role INTO v_existing
  FROM public.organization_members
  WHERE organization_id = v_inv.organization_id AND user_id = v_user;

  IF NOT FOUND THEN
    INSERT INTO public.organization_members (organization_id, user_id, role)
    VALUES (v_inv.organization_id, v_user, v_inv.role);
    v_created := true;
  END IF;
  -- else: membership already exists and is left exactly as it is. See the
  -- header. An invitation is not a role-change instrument.

  -- Marked accepted in both branches. An invitation that stays pending after
  -- being presented is a token that can be replayed, and the replay is the
  -- interesting case precisely when the user is already a member.
  UPDATE public.organization_invitations
  SET status = 'accepted', updated_at = now()
  WHERE id = v_inv.id;

  INSERT INTO public.audit_logs (organization_id, user_id, action, resource, details)
  VALUES (v_inv.organization_id, v_user, 'invitation.accept', 'invitation',
          jsonb_build_object(
            'invitation_id', v_inv.id,
            'role', v_inv.role,
            'membership_created', v_created,
            'existing_role', v_existing));

  RETURN jsonb_build_object(
    'organization_id', v_inv.organization_id,
    'membership_created', v_created,
    -- The role they actually hold now, which is NOT necessarily the invited
    -- role. Saying otherwise would put a wrong permission set on the screen.
    'role', COALESCE(v_existing, v_inv.role)
  );
END;
$$;

-- ---------------------------------------------------------------------------
-- 9. Public wrappers
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.create_invitation(
  p_organization_id UUID,
  p_email TEXT,
  p_role public.organization_role
) RETURNS JSONB
LANGUAGE sql SECURITY DEFINER SET search_path = public, private, pg_temp
AS $$ SELECT private.create_invitation(p_organization_id, p_email, p_role); $$;

CREATE OR REPLACE FUNCTION public.revoke_invitation(p_invitation_id UUID)
RETURNS JSONB
LANGUAGE sql SECURITY DEFINER SET search_path = public, private, pg_temp
AS $$ SELECT private.revoke_invitation(p_invitation_id); $$;

CREATE OR REPLACE FUNCTION public.accept_invitation(p_token TEXT)
RETURNS JSONB
LANGUAGE sql SECURITY DEFINER SET search_path = public, private, pg_temp
AS $$ SELECT private.accept_invitation(p_token); $$;

-- ---------------------------------------------------------------------------
-- 10. Close the direct-write hole
-- ---------------------------------------------------------------------------

-- This is the load-bearing statement of the migration. Everything above is
-- only enforcement if the table cannot be written around it.
REVOKE INSERT, UPDATE, DELETE ON public.organization_invitations FROM authenticated;

-- `anon` held SELECT on this table. The row policy requires
-- `auth.role() = 'authenticated'`, so it returned nothing and the grant was
-- inert — but a grant that only a policy makes safe is one policy edit away
-- from being a leak of every pending invitation's address, role and issuer.
-- An unauthenticated caller has no reason to read invitations: accepting one
-- requires a session, so the invitee signs in first and arrives as
-- `authenticated`.
REVOKE ALL ON public.organization_invitations FROM anon;

-- The policies are dropped too. A policy that permits a write for which no
-- grant exists is dead code that reads like live authorization, and the next
-- person to restore a grant would silently restore the hole with it.
DROP POLICY IF EXISTS "Owners and Admins can create invitations" ON public.organization_invitations;
DROP POLICY IF EXISTS "Owners and Admins can update invitations" ON public.organization_invitations;

-- SELECT stays: an admin listing pending invitations is legitimate, and the
-- existing SELECT policy already scopes rows to the caller's organization.
-- Note what that policy does NOT permit: the invitee cannot read their own
-- invitation before they are a member. That is intentional — they do not need
-- to, because they hold the token, and `accept_invitation` is the only thing
-- that needs to resolve it.

GRANT EXECUTE ON FUNCTION public.create_invitation(UUID, TEXT, public.organization_role) TO authenticated;
GRANT EXECUTE ON FUNCTION public.revoke_invitation(UUID) TO authenticated;
GRANT EXECUTE ON FUNCTION public.accept_invitation(TEXT) TO authenticated;

REVOKE ALL ON FUNCTION private.create_invitation(UUID, TEXT, public.organization_role) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION private.revoke_invitation(UUID) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION private.accept_invitation(TEXT) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION private.hash_invitation_token(TEXT) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION private.new_invitation_token() FROM PUBLIC, anon, authenticated;
